// --- Script ---
try{if(localStorage.get("__framer_force_showing_editorbar_since")){const n=document.createElement("link");n.rel = "modulepreload";n.href="https://framer.com/edit/init.mjs";document.head.appendChild(n)}}catch(e){}

// --- Script ---
(()=>{function i(){for(let e of document.querySelectorAll("[data-framer-original-sizes]")){let t=e.getAttribute("data-framer-original-sizes");t===""?e.removeAttribute("sizes"):e.setAttribute("sizes",t),e.removeAttribute("data-framer-original-sizes")}}function a(){window.__framer_onRewriteBreakpoints=i}return a})()()

// --- Script ---
!function(){var l="framer_variant";function u(a,r){let n=r.indexOf("#"),e=n===-1?r:r.substring(0,n),o=n===-1?"":r.substring(n),t=e.indexOf("?"),m=t===-1?e:e.substring(0,t),d=t===-1?"":e.substring(t),s=new URLSearchParams(d),h=new URLSearchParams(a);for(let[i,g]of h)s.has(i)||i!==l&&s.append(i,g);let c=s.toString();return c===""?e+o:m+"?"+c+o}var w='div#main a[href^="#"],div#main a[href^="/"],div#main a[href^="."]',f="div#main a[data-framer-preserve-params]",p=document.currentScript?.hasAttribute("data-preserve-internal-params");if(window.location.search&&!navigator.webdriver&&!/bot|-google|google-|yandex|ia_archiver|crawl|spider/iu.test(navigator.userAgent)){let a=document.querySelectorAll(p?`${w},${f}`:f);for(let r of a){let n=u(window.location.search,r.href);r.setAttribute("href",n)}}
}()

// --- Script ---
var animator=(()=>{var O=(e,r,t)=>t>r?r:t<e?e:t;var j=()=>{};function W(e){let r;return()=>(r===void 0&&(r=e()),r)}var q=e=>e;var V=e=>e*1e3,D=e=>e/1e3;function X(e,r){return r?e*(1e3/r):0}var Y=e=>Array.isArray(e)&&typeof e[0]=="number";var H={value:null,addProjectionMetrics:null};var Z={layout:0,mainThread:0,waapi:0};var L=(e,r,t=10)=>{let o="",s=Math.max(Math.round(r/t),2);for(let n=0;n<s;n++)o+=Math.round(e(n/(s-1))*1e4)/1e4+", ";return`linear(${o.substring(0,o.length-2)})`};function R(e){let r=0,t=50,o=e.next(r);for(;!o.done&&r<2e4;)r+=t,o=e.next(r);return r>=2e4?1/0:r}function fe(e,r=100,t){let o=t({...e,keyframes:[0,r]}),s=Math.min(R(o),2e4);return{type:"keyframes",ease:n=>o.next(s*n).value/r,duration:D(s)}}var Ee=5;function ce(e,r,t){let o=Math.max(r-Ee,0);return X(t-e(o),r-o)}var u={stiffness:100,damping:10,mass:1,velocity:0,duration:800,bounce:.3,visualDuration:.3,restSpeed:{granular:.01,default:2},restDelta:{granular:.005,default:.5},minDuration:.01,maxDuration:10,minDamping:.05,maxDamping:1};var _=.001;function le({duration:e=u.duration,bounce:r=u.bounce,velocity:t=u.velocity,mass:o=u.mass}){let s,n;j(e<=V(u.maxDuration),"Spring duration must be 10 seconds or less","spring-duration-limit");let i=1-r;i=O(u.minDamping,u.maxDamping,i),e=O(u.minDuration,u.maxDuration,D(e)),i<1?(s=m=>{let p=m*i,c=p*e,l=p-t,x=z(m,i),g=Math.exp(-c);return _-l/x*g},n=m=>{let c=m*i*e,l=c*t+t,x=Math.pow(i,2)*Math.pow(m,2)*e,g=Math.exp(-c),y=z(Math.pow(m,2),i);return(-s(m)+_>0?-1:1)*((l-x)*g)/y}):(s=m=>{let p=Math.exp(-m*e),c=(m-t)*e+1;return-_+p*c},n=m=>{let p=Math.exp(-m*e),c=(t-m)*(e*e);return p*c});let f=5/e,a=Ce(s,n,f);if(e=V(e),isNaN(a))return{stiffness:u.stiffness,damping:u.damping,duration:e};{let m=Math.pow(a,2)*o;return{stiffness:m,damping:i*2*Math.sqrt(o*m),duration:e}}}var ke=12;function Ce(e,r,t){let o=t;for(let s=1;s<ke;s++)o=o-e(o)/r(o);return o}function z(e,r){return e*Math.sqrt(1-r*r)}var Be=["duration","bounce"],Ie=["stiffness","damping","mass"];function ue(e,r){r

// --- Script ---
(()=>{function c(i,o,s){if(window.__framer_disable_appear_effects_optimization__||typeof animator>"u")return;let e={detail:{bg:document.hidden}};requestAnimationFrame(()=>{let a="framer-appear-start";performance.mark(a,e),animator.animateAppearEffects(JSON.parse(window.__framer__appearAnimationsContent.text),(m,p,d)=>{let t=document.querySelector(m);if(t)for(let[r,f]of Object.entries(p))animator.startOptimizedAppearAnimation(t,r,f,d[r])},i,o,s&&window.matchMedia("(prefers-reduced-motion:reduce)").matches===!0,animator.getActiveVariantHash(JSON.parse(window.__framer__breakpoints.text)));let n="framer-appear-end";performance.mark(n,e),performance.measure("framer-appear",{start:a,end:n,detail:e.detail})})}return c})()("data-framer-appear-id","__Appear_Animation_Transform__",false)

